spring:
  datasource:
#    url: jdbc:mysql://real-server:3306/baeminchan?useSSL=false
#    username:
#    password:

jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    org.hibernate: error