spring:
  datasource:
    url: jdbc:mysql://localhost:3306/baeminchan?useSSL=false
    username: minsungryu
    password: woowa

jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org.hibernate:
      - debug
      - type.descriptor.sql.BasicBinder: trace