spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver

  profiles:
    active: local

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  servlet:
    session:
      tracking-modes: cookie

handlebars:
  suffix: .html
  cache: false
  expose-session-attributes: true